Move the includes out of the namespace (#4)
This causes `unistd`'s functions, etc. to be in the `udmpparser` namespace which causes issues on OSX in one other project I am working on:
```
utils.cc:597:26: error: use of undeclared identifier 'readlink'; did you mean 'udmpparser::readlink'?
  const ssize_t Length = readlink("/proc/self/exe", ExePathBuffer.data(),
                         ^~~~~~~~
                         udmpparser::readlink
/Applications/Xcode_14.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/unistd.h:627:10: note: 'udmpparser::readlink' declared here
ssize_t  readlink(const char * __restrict, char * __restrict, size_t);
         ^
1 error generated.
```

It also updates / fixes the CI.